#!/usr/bin/env bash


# wireless_devices: list wireless devices
wireless_devices() {
    ls /sys/class/net | grep wl
}


# ethernet_devices: list ethernet devices
ethernet_devices() {
    ls /sys/class/net | grep en
}


# is_operational: check if a ethernet device is operational
is_operational() {
    local carrier=$(cat /sys/class/net/$1/carrier)
    local operstate=$(cat /sys/class/net/$1/operstate)

    if [[ $carrier -eq 1 && $operstate == "up" ]]; then
        echo true
    else
        echo false
    fi
}


# has_cabled_connection: check for cabled connection
has_cabled_connection() {
    local cabled_ethernet=false
    for device in $(ethernet_devices); do
        if is_operational $device; then
            cabled_ethernet=true
        fi
    done

    echo cabled_ethernet
}


# has_internet_connection: check for internet connection
has_internet_connection() {
    wget -q --spider http://google.com
    if [[ $? -eq 0 ]]; then
        echo true
    else
        echo false
    fi
}


# is_hotspot_active: check if hotspot is active
is_hotspot_active() {
    status &> /dev/null
    if [[ $? -eq 0 ]]; then
        echo true
    else
        echo false
    fi
}


# start: start the hotspot
start() {
    local ssid="$1"
    local password="$2"

    # if there's no cabled internet, do nothing
    if ! $(has_cabled_connection) || ! $(has_internet_connection); then
        exit
    fi

    # make sure that wifi adaptor is enabled
    nmcli radio wifi on

    # if the hotspot is already on, do nothing
    if $(is_hotspot_active); then
        echo "info: the WiFi hotspot is already on"
        exit
    fi

    # start the wifi hotspot
    if [[ $# -eq 0 ]]; then
        nmcli device wifi hotspot
    elif [[ $# -eq 2 ]]; then
        nmcli device wifi hotspot ssid $ssid password $password
    else
        echo "usage: hotspot start <ssid> <password>"
    fi
}


# stop: stop the hotspot
stop() {
    if [[ $# -ne 0 ]]; then
        echo "usage: hotspot stop"
        echo "error: too many arguments"
    fi

    # if hotspot is active, turn it off
    if $(is_hotspot_active); then
        # switch the wifi interface off and on
        nmcli radio wifi off
        nmcli radio wifi on
    fi
}


status() {
    if [[ $# -eq 0 ]]; then
        nmcli device wifi show-password
    else
        echo "usage: hotspot status"
        echo "error: too many arguments"
    fi
}


usage() {
    cat <<HELP_USAGE
usage: hotspot COMMAND

List of commands :

start           Start a WiFi hotspot
stop            Stop any running WiFi hotspot
status          Check the status of the WiFi hotspot
HELP_USAGE
}


main() {
    if [[ $# -eq 0 ]]; then
        usage
    elif [[ $1 == "start" ]]; then
        start "${@:2}"
    elif [[ $1 == "stop" ]]; then
        stop "${@:2}"
    elif [[ $1 == "status" ]]; then
        status "${@:2}"
    else
        echo "error: unknown command $1"
    fi
}


main "$@"
